### ISSUE TITLE
Feature Request: Device Tracker

### ISSUE THREAD

**Issue by meistermolli** [henfiber/hass_speedport_plus_cli#1]
Hi there,
i have a feature Request.
Because of Company change in DSL I have to use Speedport Pro Plus.

in the past I used the Fritz!Box 7590 and was able to do some Device Tracking in Homeassistant.
https://www.home-assistant.io/integrations/fritz/

Do you think this is possible with your 
hass_speedport_plus_cli ?

Thanks for watching.

meistermolli

**Comment by henfiber** [comment]
I don't recall Speedport plus exposing any info about connected devices. 

You could maybe use the ping or nmap integrations, or maybe keep the Fritzbox behind Speedport Plus (with Speedport Plus in bridge mode or Fritzbox in DMZ).

**Comment by meistermolli** [comment]
ok thank you.
